baseURL: https://madelongorter.github.io/
languageCode: en-us
title: Portfolio Website
theme: PaperMod



menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: Social Robot Design
      url: /Social Robot Design
      weight: 2
    - name: Mastering Tinkering
      url: /MasteringTinkering
      weight: 3      
    - name: Search
      url: /search
      weight: 4   

params:
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  defaultTheme: dark
  profileMode:
    enabled: true
    title: "Madelon Gorter" # optional default will be site title
    subtitle: "Welcome to my portfolio website for the Mastering Tinkering and Social Robot Design courses!"
    imageUrl: "img/Masterskip.JPEG" # optional
    imageTitle: "Profile picture" # optional
    imageWidth: 400 # custom size
    imageHeight: 400 # custom size


  socialIcons: # optional
    - name: linkedin
      url: https://www.linkedin.com/in/madelon-gorter-b377bb272/ 
    - name: instagram
      url: https://www.instagram.com/madelon.gorter/
    - name: email
      url: mailto:m.gorter@student.utwente.nl


outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

