baseURL = 'https://abilitytechlab.github.io/'
languageCode = 'en-us'
title = 'Coat Assistant'
theme= 'PaperMod'


[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "/about"
  weight = 2

  [[menu.main]]
  name = "Documentation"
  url = "/documentation"
  weight = 3

  [[menu.main]]
  name = "Contribute"
  url = "/contribute"
  weight = 4
  
  [[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 5
  
  [[menu.main]]
  name = "Post"
  url = "/post"
  weight = 6

  
  [params]
  defaultTheme = "dark"

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Welcome to my website."

  [[params.socialIcons]]
    name = "email"
    url = "mailto:m.gorter@student.utwente.nl"
